name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            echo "package-lock.json found — using npm ci"
            npm ci
          else
            echo "No package-lock.json — falling back to npm install"
            npm install
          fi
      - name: Lint (non-failing)
        run: npm run lint
      - name: Run tests
        run: npm test --silent
      - name: Build
        run: npm run build
      - name: Upload dist artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
