name: Publish pages (manual)

on:
  workflow_dispatch:
    inputs:
      prepare:
        description: 'Prepare pages artifacts (build into docs/)'
        required: false
        default: 'true'

jobs:
  prepare-pages:
    name: Prepare Pages artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check for in-progress Pages deployment
        run: |
          set -euo pipefail
          echo "Installing jq for JSON parsing..."
          sudo apt-get update && sudo apt-get install -y jq
          echo "Checking for in-progress GitHub Pages deployments..."
          DEPLOYMENTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/deployments?environment=github-pages")
          echo "$DEPLOYMENTS" | jq -r '.[] | select(.status=="in_progress") | .id' > /tmp/in_progress_ids || true
          if [ -s /tmp/in_progress_ids ]; then
            echo "Found in-progress Pages deployments (ids):"
            cat /tmp/in_progress_ids
            # Cancel each in-progress deployment by marking a status as inactive
            while read -r dep_id; do
              echo "Cancelling deployment $dep_id"
              curl -s -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" \
                -d '{"state":"inactive","description":"Cancelled by workflow to avoid collision"}' \
                "https://api.github.com/repos/${{ github.repository }}/deployments/'$dep_id'/statuses"
            done < /tmp/in_progress_ids
          else
            echo "No in-progress Pages deployments found."
          fi

      - name: Install dependencies
        run: npm ci --silent

      - name: Build
        run: npm run build

      - name: Prepare docs folder
        if: ${{ inputs.prepare == 'true' }}
        run: |
          npm run docs:clean
          node dist/repo-metrics.js . --output-prefix docs/metrics || true

      - name: Upload artifacts (docs)
        if: ${{ inputs.prepare == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: pages-docs
          path: docs/

      - name: Upload artifacts (metrics)
        uses: actions/upload-artifact@v4
        with:
          name: metrics-artifacts
          path: metrics/

      - name: Summary
        run: |
          echo "Prepared artifacts. Download them from the Actions run's Artifacts section."
