name: Publish pages (manual)

on:
  workflow_dispatch:
    inputs:
      prepare:
        description: 'Prepare pages artifacts (build into docs/)'
        required: false
        default: 'true'

jobs:
  prepare-pages:
    name: Prepare Pages artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check for in-progress Pages deployment
        run: |
          set -euo pipefail
          echo "Checking for in-progress GitHub Pages deployments..."
          DEPLOYMENTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/deployments?environment=github-pages")
          IN_PROGRESS=$(echo "$DEPLOYMENTS" | jq -r '.[] | select(.status=="in_progress") | .sha' | head -n1 || true)
          if [ -n "$IN_PROGRESS" ]; then
            echo "Found in-progress Pages deployment: $IN_PROGRESS"
            echo "Failing early to avoid collision. Cancel the deployment or retry later."
            exit 1
          fi

      - name: Install dependencies
        run: npm ci --silent

      - name: Build
        run: npm run build

      - name: Prepare docs folder
        if: ${{ inputs.prepare == 'true' }}
        run: |
          npm run docs:clean
          node dist/repo-metrics.js . --output-prefix docs/metrics || true

      - name: Upload artifacts (docs)
        if: ${{ inputs.prepare == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: pages-docs
          path: docs/

      - name: Upload artifacts (metrics)
        uses: actions/upload-artifact@v4
        with:
          name: metrics-artifacts
          path: metrics/

      - name: Summary
        run: |
          echo "Prepared artifacts. Download them from the Actions run's Artifacts section."
